name: Publish Docker Images
on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker Images to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Environment
        id: setup
        env:
          REGISTRY: "docker.pkg.github.com"
          REPOSITORY: ${{ github.repository }}
        run: |
          echo ::set-output name=registry::"${{ env.REGISTRY }}"
          echo ::set-output name=version::"$(echo "$GITHUB_REF" | sed 's*refs/heads/**g; s*refs/tags/**g;')"
          echo ::set-output name=uri_prefix::"${{ env.REGISTRY }}/$(echo '${{ env.REPOSITORY }}' | tr '[:upper:]' '[:lower:]')"

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ steps.setup.outputs.registry }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build/Push to GitHub Packages
        env:
          VERSION: ${{ steps.setup.outputs.version }}
          IMAGES: terragrunt-aws,terragrunt-azm
        shell: bash
        run: |
          for image in $(echo '${{ env.IMAGES }}' | sed "s/,/ /g"); do
            uri=${{ steps.setup.outputs.uri_prefix }}/$image
            docker build -t $uri:${{ env.VERSION }} -t $uri:latest -f ./containers/$image.dockerfile ./containers
            docker push $uri:${{ env.VERSION }}
          done
