name: Publish Docker Images
on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Environment
        id: setup
        env:
          REGISTRY: "docker.pkg.github.com"
          REPOSITORY: ${{ github.repository }}
        run: |
          echo ::set-output name=registry::"${{ env.REGISTRY }}"
          echo ::set-output name=version::"$(echo "$GITHUB_REF" | sed 's*refs/heads/**g; s*refs/tags/**g;')"
          echo ::set-output name=uri_prefix::"${{ env.REGISTRY }}/$(echo '${{ env.REPOSITORY }}' | tr '[:upper:]' '[:lower:]')"

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ steps.setup.outputs.registry }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build/Push to GitHub Packages (terragrunt-azm)
        env:
          URI: ${{ steps.setup.outputs.uri_prefix }}/terragrunt-azm:${{ steps.setup.outputs.version }}
        run: |
          docker build -t ${{ env.URI }} -f ./docker/terragrunt-azm.dockerfile .
          docker push ${{ env.URI }}
